name = "asset-allocation"
main = "src/index.js"
compatibility_date = "2024-09-23"

[assets]
directory = "./public"
binding = "ASSETS"

[[d1_databases]]
binding = "DB" # Available in your Worker on env.DB
database_name = "asset-db"
database_id = "731e746f-7fcc-4f16-a209-79d3a2eaa1bb" 
